repos:
  -   repo: local
      hooks:
        # See https://pre-commit.com/#repository-local-hooks
        - id: run test
          name: Run test
          entry: npm test
          pass_filenames: false
          language: node
          always_run: true
#          verbose: true
        - id: shellcheck
          name: shellcheck
          description: Test shell scripts with shellcheck
          entry: shellcheck
          language: python
          types: [shell]
          require_serial: true # shellcheck can detect sourcing this way
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
